test_format = 1.0

[default]

    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------

    test_upgrade_from.0f1e8c0d23500b4ec4aa8085c287fac1adbe0db8.name = "Upgrade from 2022.06.09~ynh"
