test_format = 1.0

[default]

    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------

    test_upgrade_from.5b6368a92174768c22bd2fa97e327d822a8d42f3.name = "Upgrade from 2023.02.02"
